spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms2
    username: root
    password: lsk123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    cache: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
server:
  tomcat:
    max-swallow-size: 100MB
  port: 8200
mybatis:
  configuration:
    map-underscore-to-camel-case: true
